USE RESTAURANT
GO

--solution: set transaction isolation level to read commited
SET TRAN ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM MenuItem
WAITFOR DELAY '00:00:05'
SELECT * FROM MenuItem
COMMIT TRAN

