USE RESTAURANT
GO

ALTER DATABASE RESTAURANT SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE MenuItem SET name='Chicken Wings' WHERE itemID=5
WAITFOR DELAY '00:00:05'
COMMIT TRAN

--ALTER DATABASE RESTAURANT SET ALLOW_SNAPSHOT_ISOLATION OFF
--UPDATE MenuItem SET name='Crispy Strips' WHERE itemID=5
--SELECT * FROM MenuItem